### ISSUE TITLE
Запуск под Rocky Linux 8.9. /bin/sh: google-chrome: command not found

### ISSUE THREAD

**Issue by alexusbbb** [jekeam/auto_daily_check_in_tanki#3]
Приветствую
Пытаюсь запустить скрипт под OS Rocky Linux 8.9. (В дальнейшем хотел написать Dokerfile для запуска в контейнере) Пока безуспешно.
Выдаёт ошибку:  **/bin/sh: google-chrome: command not found**
Лог ниже
```
[root@RL89-2 auto_daily_check_in_tanki]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

```
(venv) [root@RL89-2 auto_daily_check_in_tanki]# python3 --version
Python 3.11.5
```

```
(venv) [root@RL89-2 auto_daily_check_in_tanki]# pip list
Package              Version
-------------------- -----------
attrs                23.2.0
certifi              2024.2.2
cffi                 1.16.0
charset-normalizer   3.3.2
cryptography         42.0.7
h11                  0.14.0
idna                 3.7
outcome              1.3.0.post0
packaging            24.0
pip                  24.0
pycparser            2.22
pyOpenSSL            24.1.0
PySocks              1.7.1
python-dotenv        1.0.1
requests             2.31.0
selenium             4.4.0
selenium-stealth     1.0.6
setuptools           65.5.1
sniffio              1.3.1
sortedcontainers     2.4.0
trio                 0.25.0
trio-websocket       0.11.1
urllib3              1.26.18
urllib3-secure-extra 0.1.0
webdriver-manager    4.0.0
wsproto              1.2.0
```

При запуске выдаёт ошибку:

```
(venv) [root@RL89-2 auto_daily_check_in_tanki]# python3 main.py
2024-05-09 11:00:06,755 [INFO] Запуск драйвера
/bin/sh: google-chrome: command not found
/bin/sh: google-chrome-stable: command not found
/bin/sh: google-chrome-beta: command not found
/bin/sh: google-chrome-dev: command not found
/bin/sh: google-chrome: command not found
/bin/sh: google-chrome-stable: command not found
/bin/sh: google-chrome-beta: command not found
/bin/sh: google-chrome-dev: command not found
/bin/sh: google-chrome: command not found
/bin/sh: google-chrome-stable: command not found
/bin/sh: google-chrome-beta: command not found
/bin/sh: google-chrome-dev: command not found
/bin/sh: google-chrome: command not found
/bin/sh: google-chrome-stable: command not found
/bin/sh: google-chrome-beta: command not found
/bin/sh: google-chrome-dev: command not found
/bin/sh: google-chrome: command not found
/bin/sh: google-chrome-stable: command not found
/bin/sh: google-chrome-beta: command not found
/bin/sh: google-chrome-dev: command not found
2024-05-09 11:00:09,128 [ERROR] Traceback (most recent call last):
  File "/opt/auto_daily_check_in_tanki/main.py", line 194, in <module>
    driver = driver_init(headless=1)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/auto_daily_check_in_tanki/main.py", line 67, in driver_init
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/opt/auto_daily_check_in_tanki/venv/lib64/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/auto_daily_check_in_tanki/venv/lib64/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/opt/auto_daily_check_in_tanki/venv/lib64/python3.11/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/opt/auto_daily_check_in_tanki/venv/lib64/python3.11/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
```

Нужен установленный браузер Chrome?

**Comment by jekeam** [comment]
Судя по ошибке, в вашей системе не установлен браузер Google Chrome. Selenium пытается найти исполняемый файл Chrome, но не может его найти, что приводит к сбою при инициализации драйвера.

Можете доработать это в 
```

    driver = webdriver.Chrome(
        service=ChromeService(ChromeDriverManager().install()),     
        options=options,
    )
```

Либо поставить бразуер.
